export const GRID_CONSTANTS = {
    DEFAULT_ROW_HEIGHT: 50,
    DEFAULT_COLUMN_WIDTH: 100,
    MIN_COLUMN_WIDTH: 50,
    MAX_COLUMN_WIDTH: 300,
    OVERSCAN_ROW_COUNT: 5,
    OVERSCAN_COLUMN_COUNT: 3,
    CHUNK_SIZE: 1000,
    CACHE_SIZE: 10000,
    SCROLL_THROTTLE_MS: 16, // ~60fps
} as const;

export const CELL_CONSTANTS = {
    BORDER_WIDTH: 1,
    BORDER_COLOR: '#e0e0e0',
    BACKGROUND_COLOR: '#ffffff',
    TEXT_COLOR: '#000000',
    SKELETON_COLOR: '#f0f0f0',
    SKELETON_HIGHLIGHT_COLOR: '#f8f8f8',
} as const;

export const PERFORMANCE_CONSTANTS = {
    MAX_RENDERED_CELLS: 500,
    DEBOUNCE_SCROLL_MS: 100,
    ANIMATION_DURATION_MS: 300,
} as const;
